### ISSUE TITLE
NUMPAD keys aren't being detected

### ISSUE THREAD

**Issue by Hedwig7s** [Potat05/PianoPlayer#1]
Can't even use it

**Comment by Potat05** [comment]
Try turning num lock on (The key is at the top of the numpad) Numlock changes the functions of the numpad keys so it needs to be on for the program to work

**Comment by Hedwig7s** [comment]
> Try turning num lock on (The key is at the top of the numpad) Numlock changes the functions of the numpad keys so it needs to be on for the program to work

Tried that
Still nope
